[build]
  publish = "./public"
  command = "npm run bootstrap && npx netlify-lambda build lambda/ && npm run build"
  functions = "./functions"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
    Strict-Transport-Security = '''
    max-age=31536000;
    includeSubDomains;'''

    Content-Security-Policy = '''
    frame-ancestors
      'self';
    upgrade-insecure-requests
      1;
    script-src
      'self'
      'report-sample'
      'unsafe-inline'
      https://cdn.bizible.com/scripts/bizible.js
      https://cdn.leadmanagerfx.com/js/mcfx/4879
      https://cdn.statuspage.io/se-v2.js
      https://connect.facebook.net/en_US/fbevents.js
      https://d.adroll.com/consent/check/
      https://*.clarity.ms
      https://googleads.g.doubleclick.net/pagead/viewthroughconversion/*/
      https://j.6sc.co/6si.min.js
      https://munchkin.marketo.net/*/munchkin.js
      https://platform.twitter.com/oct.js
      https://s.adroll.com/j/roundtrip.js
      https://snap.licdn.com/li.lms-analytics/insight.min.js
      https://static.ads-twitter.com/uwt.js
      https://tag.demandbase.com/*.min.js
      https://tracking.g2crowd.com/attribution_tracking/conversions/*.js
      https://ws.zoominfo.com/pixel/*
      https://www.clarity.ms/tag/*
      https://www.google-analytics.com/analytics.js
      https://www.googleadservices.com/pagead/conversion_async.js
      https://www.googletagmanager.com/gtm.js;
    style-src
      'self'
      'report-sample'
      'unsafe-inline';
    object-src
      'none';
    frame-src
      'self';
    child-src
      'self';
    img-src
      'self'
      data:*
      *;
    font-src
      'self'
      *.cloudfront.net;
    connect-src
      'self'
      *;
    manifest-src
      'self';
    base-uri
      'self';
    form-action
      'self';
    media-src
      'self';
    prefetch-src
      'self';
    worker-src
      'none';
    report-uri
      https://o104929.ingest.sentry.io/api/6351005/security/?sentry_key=4ffc1bf32c374fb18a9cf3c51f65cdf6;
    '''

# Run `npm run publish` to re-index in algolia
# [context.production]
#   publish = "./public"
#   command = "npm run bootstrap && npx netlify-lambda build lambda/ && npm run publish"
#   functions = "./functions"
