FORMAT: 1A
title: Account
description: Get your SparkPost account information, including subscription status and quota usage.

# Group Account

Retrieve information regarding your SparkPost account and set account options.

## Account Object

+ Data Structure: Attributes
    + customer_id (number) - Account ID
    + company_name (string) - Account holder company name
    + country_code (string) - Account holder 2-letter country code
    + anniversary_date (string) - ISO date of billing anniversary
    + created (string) - ISO date account was created
    + updated (string) - ISO date account details were last updated
    + status  (string) - Account status.
        + Default: active
    + status_updated (string) - ISO date status was last updated
    + status_reason_category (string) - Category for some account statuses, e.g. 'NONPAYMENT'. Empty string by default
    + service_level (string) - Account service level.
        + Default: standard
    + subscription (object) - Current subscription details.
        + name (string) - The account's plan name
        + code (string) - The account's plan code
        + plan_volume (number) - The plan's sending volume
        + effective_date (string) - ISO date of when this subscription has been or will be effective
        + self_serve (boolean) - `false` if the account is manually billed
        + type (string) - Type of subscription.
            + Default: default
    + pending_subscription (object) - Details regarding a pending subscription upgrade or downgrade.
    + options (object) - Account-level tracking settings.
        + smtp_tracking_default (boolean) - Account-level default for SMTP engagement tracking
        + rest_tracking_default (boolean) - Account-level default for REST API engagement tracking
        + transactional_unsub (boolean) - Set to `true` to include `List-Unsubscribe` header for all transactional messages by default
        + transactional_default (boolean) - Set to `true` to send messages as transactional by default
        + initial_open_pixel_tracking (boolean) - Account-level default for Initial Open tracking
        + click_tracking (boolean)
            Set to `false` to turn off click tracking (overrides smtp_tracking_default and rest_tracking_default)
    + usage (object) - Account quota usage details. Specify 'include=usage' in query string to include usage info. Usage data is not available for Enterprise accounts.
        + timestamp (string) - ISO date usage data was retrieved
        + day (object) - Daily usage report.
            + used (number) - Total messages sent in this period
            + limit (number) - Total allowance for this period
            + start (string) - ISO date when this period started
            + end (string) - ISO date when this period ends
        + month (object) - Monthly usage report.
            + used (number) - Total messages sent in this period
            + limit (number) - Total allowance for this period
            + start (string) - ISO date when this period started
            + end (string) - ISO date when this period ends
        + sandbox (object) - Sandbox domain usage report.
            + used (number) - Total messages sent over the lifetime of the account
            + limit (number) - Total allowance for the account
    + support (object) - Support entitlement details.
        + phone (boolean) - Whether account is entitled to phone support
        + online (boolean) - Whether account is entitled to online support
+ Sample

    ```json
    {
        "customer_id": 102938,
        "company_name": "Example, Inc.",
        "country_code": "US",
        "anniversary_date": "2019-01-11T08:00:00.000Z",
        "created": "2015-01-11T08:00:00.000Z",
        "updated": "2018-04-11T08:00:00.000Z",
        "status": "active",
        "status_updated": "2018-04-11T08:00:00.000Z",
        "status_reason_category": "",
        "service_level": "standard",
        "subscription": {
            "name": "500K",
            "code": "500K-0817",
            "plan_volume": 500000,
            "effective_date": "2018-04-11T08:00:00.000Z",
            "self_serve": true,
            "type": "default"
        },
        "options": {
            "smtp_tracking_default": true
        },
        "usage": {
            "timestamp": "2018-06-26T14:48:00.000Z",
            "day": {
                "limit": 1000,
                "used": 83,
                "start": "2018-06-25T15:00:00.000Z",
                "end": "2018-06-26T15:00:00.000Z"
              },
              "month": {
                "limit": 15000,
                "used": 4032,
                "start": "2018-06-03T08:00:00.000Z",
                "end": "2018-07-03T08:00:00.000Z"
            }
        },
        "support": {
            "phone": false,
            "online": false
        }
    }
    ```

### Retrieve account information [GET /v1/account{?include}]

+ Request

    + Headers

            Authorization: 14ac5499cfdd2bb2859e4476d2e5b1d2bad079bf
            Accept: application/json

+ Parameters

    + include (optional, string, `usage`) ... Additional parts of account details to include. The only valid value is currently `usage`.


+ Response 200 (application/json)

        {
            "results": {
                "customer_id": 102938,
                "company_name": "Example Inc",
                "country_code": "US",
                "anniversary_date": "2019-01-11T08:00:00.000Z",
                "created": "2018-01-11T08:00:00.000Z",
                "updated": "2018-02-11T08:00:00.000Z",
                "status": "active",
                "status_updated": "2018-12-21T13:21:41.442Z",
                "status_reason_category": "",
                "subscription": {
                    "code": "150K-0817",
                    "name": "150K",
                    "plan_volume": 150000,
                    "self_serve": "true",
                    "type": "manual"
                },
                "support": {
                    "online": true,
                    "phone": false
                },
                "pending_subscription": {
                    "code": "2.5M-0817",
                    "name": "2.5M",
                    "effective_date": "2017-04-11T00:00:00.000Z"
                },
                "options": {
                    "smtp_tracking_default": false
                },
                "usage": {
                    "timestamp": "2016-03-17T05:19:00.932Z",
                    "day": {
                        "used": 22003,
                        "limit": 50000,
                        "start": "2016-03-16T05:30:00.932Z",
                        "end": "2016-03-17T05:30:00.932Z"
                    },
                    "month": {
                        "used": 122596,
                        "limit": 1500000,
                        "start": "2018-03-11T08:00:00.000Z",
                        "end": "2016-04-11T08:00:00.000Z"
                    },
                    "sandbox": {
                        "used": 3,
                        "limit": 5
                    }

                }
            }
        }

### Update account information [PUT /v1/account]

+ Data Structure
    + company_name (string) - Company name
    + options (object) - Account-level options.
        + smtp_tracking_default (boolean) - Set to `true` to turn on SMTP engagement tracking by default
        + rest_tracking_default (boolean) - Set to `false` to turn off REST API engagement tracking by default
        + transactional_unsub (boolean) - Set to `true` to include `List-Unsubscribe` header for all transactional messages by default
        + transactional_default (boolean) - Set to `true` to send messages as transactional by default
        + initial_open_pixel_tracking (boolean) - Set to `false` to exclude the initial open tracking pixel from top of emails
        + click_tracking (boolean)
            Set to `false` to turn off click tracking (overrides smtp_tracking_default and rest_tracking_default)



+ Request

    + Headers

            Authorization: 14ac5499cfdd2bb2859e4476d2e5b1d2bad079bf
            Accept: application/json

    + Body

            {
                "company_name": "SparkPost",
                "options": {
                    "smtp_tracking_default": true
                }
            }

+ Response 200 (application/json)

        {
            "results": {
                "message": "Account has been updated"
            }
        }
