FORMAT: 1A
title: Alerts
description: Configure real-time alerts for your SparkPost account.
label: New

# Group Alerts
Alerts can be used to get notifications regarding various activities and metrics on your SparkPost account.

## Metrics
At this time, the following metrics are supported:

* Real-Time
    + monthly_sending_limit
    + block_bounce_rate
* Signals
    + health_score

Each metric group has a specific set of filters and some other values allowed.

* Real-Time
    + filters - filter_type can be 'sending_domain', 'sending_ip', or 'mailbox_provider'
    + threshold_evaluator - source must be 'raw'
* Signals
    + filters - filter_type can be 'sending_domain', 'ip_pool', or 'mailbox_provider'. Only one filter type can be selected,
        though multiple values are allowed.

* monthly_sending_limit
  + filters - must be an empty array. No filters may be applied to this metric.
  + subaccounts - must be [0].
  + any_subaccount - must be unset or set to false.

## Channels
Alerts can have a number of different notification channel types associated with them. At this time, the following channels are supported:

* emails - Sends notifications via email to up to 10 email addresses.

## Filter Object

+ Data Structure: Attributes
  + filter_type (enum) - Type of filter to apply to the alert.
    + `"sending_domain", "mailbox_provider", "sending_ip", "ip_pool"`
  + `filter_values` (array) - Set of all filter values associated with the given filter_type.

+ Sample

  ```
  {
    "filter_type": "sending_domain",
    "filter_values": [
      "sparkpost.com",
      "test.com"
    ]
  }
  ```

## Alert Object

+ Data Structure: Attributes
    + id (number) - Unique identifier of the alert.
    + name (string) - Display name of the alert.
    + subaccounts (array) - Subaccount filters applied to the alert.
    + any_subaccount (boolean) - Flag indicating all subaccounts should be evaluated for this alert.
    + metric (enum) - Metric that the alert is configured to track.
        + `"monthly_sending_limit", "health_score"`
    + muted (boolean) - Flag indicating whether the alert should be ignored for evaluation/emission.
    + filters (array) - Filter objects to apply to the alert.
    + threshold_evaluator (object) - Evaluator object for an alert with a trigger threshold.
      + operator (enum) - Operator for alert evaluation to use.
        + `"gt", "lt"`
      + source (enum) - Source of value to compare against.
        + `"raw", "day_over_day", "week_over_week"`
      + value (number) - Target value to compare against.
    + channels (object) - Channels to send alert notifications through.
        + emails (array) - Email addresses to send alert notifications to.

+ Sample

  ```
  {
    "id": 117,
    "name": "Alert Name Here",
    "subaccounts": [0, 2],
    "any_subaccount": false,
    "metric": "health_score",
    "muted": false,
    "filters": [
      {
        "filter_type": "sending_domain", 
        "filter_values": ["test.com"]
      }
    ],
    "threshold_evaluator": {
      "operator": "gt",
      "source": "raw",
      "value": 0
    },
    "channels": {
        "emails": [
            "test@sparkpost.com",
            "bigwig@test.com"
        ]
    }
  }
  ```

### Create an Alert [POST /v1/alerts]
Creates a new alert

+ Data Structure
  + name (string, required) - Display name of the alert.
  + subaccounts (array) - (Optional) Subaccount filters applied to the alert. This field must be set, or any_subaccount set to true.
  + any_subaccount (boolean) - (Optional)  Flag indicating all subaccounts should be evaluated for this alert. If subaccount is not set, this must be true.
  + metric (enum, required) - Metric that the alert is configured to track.
      + `"monthly_sending_limit", "health_score"`
  + muted (boolean, required) - Flag indicating whether the alert should be ignored.
  + filters (array, required) - Filter objects to apply to the alert.
  + threshold_evaluator (object, required) - Evaluator object for an alert with a trigger threshold.
    + operator (enum, required) - Operator for alert evaluation to use.
      + `"gt", "lt"`
    + source (enum, required) - Source of value to compare against.
      + `"raw", "day_over_day", "week_over_week"`
    + value (number, required) - Target value to compare against.
  + channels (object, required) - Channels to send alert notifications through.
    + emails (array) - Email addresses to send alert notifications to.


+ Request (application/json)
  + Body
  {
    "name": "Alert Name Here",
      "subaccounts": [1],
      "any_subaccount": false,
      "metric": "health_score",
      "muted": false,
      "filters": [
        {
          "filter_type": "sending_domain", 
          "filter_values": ["test.com"]
        }
      ],
      "threshold_evaluator": {
        "operator": "gt",
        "source": "raw",
        "value": 0
      },
      "channels": {
        "emails": [
            "test@sparkpost.com",
            "bigwig@test.com"
        ]
      }
  }

+ Response 200 (application/json)
  {
    "results": {
      "id": 117,
    }
  }

### Retrieve an Alert [GET /v1/alerts/{id}]
Retrieve full information about a single alert.

+ Parameters
    + id (required, number, `117`)

+ Response 200 (application/json)
  {
    "name": "Alert Name Here",
    "subaccounts": [0],
    "any_subaccount": false,
    "metric": "health_score",
    "muted": false,
    "filters": [
      {
        "filter_type": "sending_domain", 
        "filter_values": ["test.com"]
      }
    ],
    "threshold_evaluator": {
      "operator": "gt",
      "source": "raw",
      "value": 0
    },
    "channels": {
      "emails": [
        "test@sparkpost.com",
        "bigwig@test.com"
      ]
    }
  }

### Retrieve Alerts [GET /v1/alerts/]
Retrieve full information about all of your alerts.

+ Response 200 (application/json)
  [
    {
      "id": 117
      "name": "Alert Name Here",
      "subaccounts": [5],
      "any_subaccount": false,
      "metric": "health_score",
      "muted": false,
      "filters": [
        {
          "filter_type": "sending_domain", 
          "filter_values": ["test.com"]
        }
      ],
      "threshold_evaluator": {
        "operator": "gt",
        "source": "raw",
        "value": 0
      },
      "channels": {
        "emails": [
            "test@sparkpost.com",
            "bigwig@test.com"
        ]
      }
    },
    {
      "id": 343
      "name": "Other Alert Name Here",
      "subaccounts": [0],
      "any_subaccount": false,
      "metric": "monthly_sending_limit",
      "muted": true,
      "filters": [],
      "threshold_evaluator": {
        "operator": "gt",
        "source": "raw",
        "value": 90
      },
      "channels": {
        "emails": [
            "test@sparkpost.com"
        ]
      } 
    }
  ]

### Delete an Alert [DELETE /v1/alerts/{id}]
Delete a single alert.

+ Parameters
    + id (required, number, `117`)

+ Response 200 (application/json)
  {
    "results": {
      "id": 117
    }
  }

### Update an Alert [PUT /v1/alerts/{id}]
Updates an existing alert by ID. All fields are optional, but if an updated value conflicts with an existing one an error will be thrown.

+ Data Structure
  + name (string) - Display name of the alert.
  + subaccounts (array) - (Optional) Subaccount filters applied to the alert. This field must be set, or any_subaccount set to true.
  + any_subaccount (boolean) - (Optional)  Flag indicating all subaccounts should be evaluated for this alert. If subaccount is not set, this must be true.
  + metric (enum) - Metric that the alert is configured to track.
      + `"monthly_sending_limit", "health_score"`
  + muted (boolean) - Flag indicating whether the alert should be ignored.
  + filters (array) - Filter objects to apply to the alert.
  + threshold_evaluator (object) - Evaluator object for an alert with a trigger threshold.
    + operator (enum) - Operator for alert evaluation to use.
      + `"gt", "lt"`
    + source (enum) - Source of value to compare against.
      + `"raw", "day_over_day", "week_over_week"`
    + value (number) - Target value to compare against.
  + channels (object) - Channels to send alert notifications through.
    + emails (array) - Email addresses to send alert notifications to.


+ Request (application/json)
  + Body
    {
      "name": "Totally different name",
      "subaccounts": [19],
      "muted": true,
      "filters": [
        {
          "filter_type": "mailbox_provider", 
          "filter_values": ["gmail.com"]
        }
      ],
      "threshold_evaluator": {
        "value": 75
      }
    }

+ Parameters
    + id (required, number, `117`)

+ Response 200 (application/json)
  {
    "name": "Totally different name",
    "subaccounts": [19],
    "any_subaccount": false,
    "metric": "health_score",
    "muted": true,
    "filters": [
      {
        "filter_type": "mailbox_provider", 
        "filter_values": ["gmail.com"]
      }
    ],
    "threshold_evaluator": {
      "operator": "gt",
      "source": "raw",
      "value": 75
    },
    "channels": {
      "emails": [
        "test@sparkpost.com",
        "bigwig@test.com"
      ]
    }
  }
