FORMAT: 1A
title: Bounce Domains
description: Manage custom bounce domains, which are used for bounce reporting.

# Group Bounce Domains
<a name="bounce-domains-api"></a>

<div class="alert alert-danger">The Bounce Domains endpoint is <strong>discontinued</strong>.  Please use the <a href="sending-domains.html">Sending Domains endpoint</a> to configure one or more verified domains to be used as custom bounce domains.</div><br>
