FORMAT: 1A
title: Events
description: TODO

# Group Events

TODO

### Data Retention

TODO

### Event Types

TODO

<MessageEvents></MessageEvents>

### Licensing

___

__The SparkPost Message Events API uses MaxMind software [MaxMind License](https://www.maxmind.com/download/geoip/database/LICENSE.txt)__

___

### Search for Message Events [GET /v1/events/message{?}]

TODO

+ Parameters
    + from
    + to
    + timezone
    + cursor
    + events
    + subaccounts
    + recipients
    + campaign_ids
    + template_ids
    + message_ids
    + transmission_ids
    + friendly_froms
    + bounce_classes
    + reason
    + subject
    + sending_domains
    + sending_ips
    + ip_pools
    + ab_test_ids
    + ab_test_version

### Documentation [GET /v1/events/message/documentation]

TODO

### Documentation [GET /v1/events/message/samples{?events}]
