FORMAT: 1A
title: Labs APIs
description: Documentation for the capabilities of SparkPost Labs.
full: true

# SparkPost Labs

We love to experiment with new ideas at SparkPost. With Labs, we release new and experimental features for you to try out. Give them a go if you're as excited about pushing email to the next level as we are. Due to their experimental nature, here are some details to keep in mind when using Labs features:

* Labs features aren't versioned, and are mainly available under the `/api/labs/` path, rather than the normal `/api/v1/` path. When it makes sense, some Labs features are available under existing API endpoints.
* Lab features are **experimental and subject to change**. We may decide to change the behavior or **discontinue it at any time**. We also may decide to incorporate Labs functionality into the core supported product.

* **Normal support channels or SLAs are not available for SparkPost Labs**. You can provide feedback via [this Google form](https://goo.gl/forms/qvTW9BbmQFsFTZB03).

## Available Labs Features
* [Snippets](/api/snippets)
