FORMAT: 1A
title: Message Events
description: Query detailed message event data for further analysis and processing.

# Group Message Events

The Message Events API has been deprecated.  Please use the [Events API](/api/events/).
