FORMAT: 1A
title: Message Events
description: Query detailed message event data for further analysis and processing.

# Group Message Events

The Message Events API has been deprecated.  Please use the [Events API](/api/events/).

Notice on May 8 2019: We are discontinuing the Message Events API on October 1, 2019. Starting on October 1 the Message Events API will return a 4xx error.  Users must switch to using the Events API instead. Events Search’s API and UI provide robust searching capabilities of the raw message event data associated with the messages you send via SparkPost.
