FORMAT: 1A
title: Sending IPs
description: Manage the sending IPs for your account and assign them to IP pools.

# Group Sending IPs

<Banner status="info"><strong><a href="https://www.sparkpost.com/enterprise-email/">SparkPost Enterprise</a></strong> customers: IPs are managed through your TAM, please contact them directly for assistance.</Banner>

## Sending IP Object

+ Data Structure
    + external_ip (string) - Public-facing IP address of this sending IP
    + hostname (string) - Reverse DNS hostname associated with this IP
    + ip_pool (string) - IP pool this sending IP is held in
    + customer_provided (boolean) - Whether this sending IP was provided by the customer.
+ Sample
    
    ```
    {
        "external_ip": "123.45.67.80",
        "hostname": "mta474a.sparkpostmail.com",
        "ip_pool": "default"
    }
    ```

## Retrieve a Sending IP [GET /v1/sending-ips/{external_ip}]

Retrieves a specific sending IP.

+ Request

    + Headers

            Authorization: aHR0cDovL2kuaW1ndXIuY29tL293UndTR3AucG5n
            Accept: application/json

+ Parameters
    + external_ip (required, string, `123.45.67.89`) ... The external IP of the sending IP


+ Response 200 (application/json)

        {
            "results": {
                "external_ip": "123.45.67.89",
                "hostname": "mta472a.sparkpostmail.com",
                "ip_pool": "cool_kids",
                "customer_provided": false
            }
        }


+ Response 400 (application/json)

        {
            "errors": [
                {
                    "message": "external ip must be a valid IPv4 address"
                }
            ]
        }

+ Response 404 (application/json)

        {
            "errors": [
                {
                    "message": "Sending IP does not exist"
                }
            ]
        }


## Update a Sending IP [PUT /v1/sending-ips/{external_ip}]

+ Data Structure
    + ip_pool (string, required) - The IP pool to add this sending IP to.

Updates which IP Pool holds the sending IP.

+ Request

    + Headers

            Authorization: aHR0cDovL2kuaW1ndXIuY29tL293UndTR3AucG5n
            Accept: application/json

    + Body

            {
                "ip_pool": "too_cool_for_pool"
            }

+ Parameters
    + external_ip (required, string, `123.45.67.89`) ... The external IP of the sending IP to update


+ Response 200 (application/json)

        {
            "results": {
                "message": "Updated IP Pool."
            }
        }

+ Response 400 (application/json)

    {
        "errors": [
            {
                "message": "IP Pool too_cool_for_pool does not exist."
            }
        ]
    }

+ Response 404 (application/json)

    {
        "errors": [
            { 
                "message": "Sending IP does not exist"
            }
        ]
    }


## List all sending IPs [GET /v1/sending-ips]

Returns a list of all sending IPs.

+ Request

    + Headers

            Authorization: aHR0cDovL2kuaW1ndXIuY29tL293UndTR3AucG5n
            Accept: application/json

+ Response 200 (application/json)

        {
            "results": [
                {
                    "external_ip": "123.45.67.89",
                    "hostname": "mta472a.sparkpostmail.com",
                    "ip_pool": "marketing",
                    "customer_provided": false
                },
                {
                    "external_ip": "123.45.67.80",
                    "hostname": "mta474a.sparkpostmail.com",
                    "ip_pool": "default",
                    "customer_provided": false
                }
            ]
        }
